BagShahr/Areas/Admin/Controllers/HomeSlidersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Security;
using System.Web.Mvc;
using DataLayer;
using DataLayer.Migrations;
using InsertShowImage;
using KooyWebApp_MVC.Classes;

namespace BagShahr.Areas.Admin.Controllers
{
	[Authorize]
	public class HomeSlidersController : Controller
	{
		private BagShahrContext db;
		SliderRepo sliderRepo;
		public HomeSlidersController()
		{
			db = new BagShahrContext();
			sliderRepo = new SliderRepo(db);

		}

		public ActionResult Index()
		{
			return View(sliderRepo.GetAllSlider());
		}
		public ActionResult Create()
		{
			return View();
		}

		[HttpPost]
		//[ValidateAntiForgeryToken]
		public ActionResult Create([Bind(Include = "Id,ImgName,ImgAlt,Title,SubTitle,CreatDate")] HomeSlider homeSlider, HttpPostedFileBase ImgUp)
		{
			if (ModelState.IsValid)
			{
				homeSlider.CreatDate = DateTime.Now;
				homeSlider.ImgName = "images.jpg";
				if (ImgUp != null && ImgUp.IsImage())
				{
					homeSlider.ImgName = Guid.NewGuid().ToString() + Path.GetExtension(ImgUp.FileName);
					ImgUp.SaveAs(Server.MapPath("/Image/slider/" + homeSlider.ImgName));
					ImageResizer img = new ImageResizer();
					img.Resize(Server.MapPath("/Image/slider/" + homeSlider.ImgName),
						Server.MapPath("/Image/slider/Thumb/" + homeSlider.ImgName
						));
				}
				sliderRepo.AddSlider(homeSlider);
				sliderRepo.Save();
				return RedirectToAction("Index");
			}
			return View(homeSlider);
		}

		public ActionResult Delete(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			HomeSlider homeSlider = sliderRepo.GetSliderById(id.Value);
			if (homeSlider == null)
			{
				return HttpNotFound();
			}
			return View(homeSlider);
		}

		[HttpPost, ActionName("Delete")]
		//[ValidateAntiForgeryToken]
		public ActionResult DeleteConfirmed(int id)
		{
			var slid = sliderRepo.GetSliderById(id);
			if (slid.ImgName != "images.jpg")
			{
				System.IO.File.Delete(Server.MapPath("/Image/slider/" + slid.ImgName));
				System.IO.File.Delete(Server.MapPath("/Image/slider/Thumb/" + slid.ImgName));
			}
			sliderRepo.DeleteSlider(slid);
			sliderRepo.Save();
			return RedirectToAction("Index");
		}
	
		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				sliderRepo.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

BagShahr/Areas/Admin/Views/HomeSliders/Create.cshtml
@model DataLayer.HomeSlider

@{
	ViewBag.Title = "اسلایدر";
}


<br />
<br />
<div class="container">
	<div class="row">
		@using (Html.BeginForm("Create", "HomeSliders", FormMethod.Post, new { enctype = "multipart/form-data" }))
		{
			@*@Html.AntiForgeryToken()*@
			<div class="col-md-8">
				<div class="panel panel-primary">
					<div class="panel-heading"><h4>ثبت اسلایدر جدید</h4></div>
					<div class="panel-body">
						<div class="form-horizontal">

							@Html.ValidationSummary(true, "", new { @class = "text-danger" })
							<div class="form-group">
								@Html.LabelFor(model => model.ImgAlt, htmlAttributes: new { @class = "control-label col-md-2" })
								<div class="col-md-10">
									@Html.EditorFor(model => model.ImgAlt, new { htmlAttributes = new { @class = "form-control" } })
									@Html.ValidationMessageFor(model => model.ImgAlt, "", new { @class = "text-danger" })
								</div>
							</div>

							<div class="form-group">
								@Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
								<div class="col-md-10">
									@Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
									@Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
								</div>
							</div>

							<div class="form-group">
								@Html.LabelFor(model => model.SubTitle, htmlAttributes: new { @class = "control-label col-md-2" })
								<div class="col-md-10">
									@Html.EditorFor(model => model.SubTitle, new { htmlAttributes = new { @class = "form-control" } })
									@Html.ValidationMessageFor(model => model.SubTitle, "", new { @class = "text-danger" })
								</div>
							</div>


							<div class="form-group">
								<div class="col-md-offset-2 col-md-10">
									<input type="submit" value="ثبت" class="btn btn-success" />
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="panel panel-primary">
					<div class="panel-heading"><h4>تصویر</h4></div>
					<img src="~/Image/images.jpg" id="imgPreviewProduct" class="thumbnail" style="margin:5px auto" />
					<div class="panel-body"><input type="file" id="imageProduct" name="ImgUp" /></div>
				</div>
			</div>
		}
	</div>
	<div>
		@Html.ActionLink("برگشت به لیست", "Index")
	</div>

	@section Scripts {
		@Scripts.Render("~/bundles/jqueryval")
		<script>
			function readURL(input) {

				if (input.files && input.files[0]) {
					var reader = new FileReader();

					reader.onload = function (e) {
						$('#imgPreviewProduct').attr('src', e.target.result);
					}

					reader.readAsDataURL(input.files[0]);
				}
			}

			$("#imageProduct").change(function () {
				readURL(this);
			});
		</script>
		<script src="/ckeditor/ckeditor.js"></script>
		<script src="/ckeditor/adapters/jquery.js"></script>
		<script>
			$(function () {
				$('#ShortDiscript').ckeditor();
			});
			$(function () {
				$('#Text').ckeditor();
			});
		</script>
	}

BagShahr/Areas/Admin/Views/HomeSliders/Delete.cshtml
@model DataLayer.HomeSlider

@{
    ViewBag.Title = "Delete";
}

<h2>حذف</h2>

<h3>آیا از حذف اسلاید مورد نظر مطمعن هستید ؟</h3>
<div>
  
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ImgName)
        </dt>

        <dd>
			<img src="~/Image/slider/thumb/@Model.ImgName" class="thumbnail" alt="Alternate Text" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImgAlt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImgAlt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @*@Html.AntiForgeryToken()*@

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("بازگشت به لیست", "Index")
        </div>
    }
</div>

BagShahr/Areas/Admin/Views/HomeSliders/Index.cshtml
@model IEnumerable<DataLayer.HomeSlider>

@{
	ViewBag.Title = "اسلایدر";
}

<br />
<br />
<a href="@Url.Action("Create")" class="btn btn-success">اسلاید جدید </a>
<br />
<br />
<table class="table">
	<tr>
		<th>
			@Html.DisplayNameFor(model => model.ImgName)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.ImgAlt)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Title)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.SubTitle)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.CreatDate)
		</th>
		<th></th>
	</tr>

	@foreach (var item in Model)
	{
		<tr>
			<td>
				<img src="~/Image/slider/thumb/@item.ImgName" alt="@item.ImgAlt" />
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.ImgAlt)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Title)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.SubTitle)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.CreatDate)
			</td>
			<td>
				<a class="btn btn-success btn-sm" href="/">نمایش </a>
				<a class="btn btn-danger btn-sm" href="@Url.Action("Delete",new {id=item.Id})">حذف</a>
			</td>
		</tr>
	}

</table>